// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ebike_demo

#ifndef _EBIKE_DEMO_UI_H
#define _EBIKE_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Home.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Fash_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * On_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Knob_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg5_png);    // assets/bg5.png
LV_IMG_DECLARE(ui_img_map_demo2_png);    // assets/map_demo2.png
LV_IMG_DECLARE(ui_img_gps_bg_png);    // assets/gps_bg.png
LV_IMG_DECLARE(ui_img_speedbg_small_png);    // assets/speedbg_small.png
LV_IMG_DECLARE(ui_img_speed_fg_small_png);    // assets/speed_fg_small.png

// FONTS
LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
