// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ebike_demo

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_BG1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Group_Header2 = NULL;
lv_obj_t * ui_Head_Group1 = NULL;
lv_obj_t * ui_Label_Time3 = NULL;
lv_obj_t * ui_Label_Temp2 = NULL;
lv_obj_t * ui_Label_Celsius2 = NULL;
lv_obj_t * ui_Label_Battery_Number1 = NULL;
lv_obj_t * ui_Label_Battery_Percent1 = NULL;
lv_obj_t * ui_Group_Driving = NULL;
lv_obj_t * ui_Group_Content = NULL;
lv_obj_t * ui_LabeL_ODO1 = NULL;
lv_obj_t * ui_Group_ODO1 = NULL;
lv_obj_t * ui_Label_ODO_Number1 = NULL;
lv_obj_t * ui_Label_km2 = NULL;
lv_obj_t * ui_Group_Map = NULL;
lv_obj_t * ui_Map_Bg = NULL;
lv_obj_t * ui_GPS_Knob2 = NULL;
lv_obj_t * ui_GPS_Knob1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label_Trip_Odo = NULL;
lv_obj_t * ui_Label_Time_Trip = NULL;
lv_obj_t * ui_Label_km3 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Speed_Number_2 = NULL;
lv_obj_t * ui_Speed_Number_1 = NULL;
lv_obj_t * ui_Label_Speed = NULL;
lv_obj_t * ui_Label_kmh1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_ImgSpeedbg = NULL;
lv_obj_t * ui_ImgSpeedfg = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BG1 = lv_img_create(ui_Home);
    lv_img_set_src(ui_BG1, &ui_img_bg5_png);
    lv_obj_set_width(ui_BG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BG1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Panel1, 61);
    lv_obj_set_height(ui_Panel1, 31);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Header2 = lv_obj_create(ui_Home);
    lv_obj_set_height(ui_Group_Header2, 24);
    lv_obj_set_width(ui_Group_Header2, lv_pct(100));
    lv_obj_set_align(ui_Group_Header2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Group_Header2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Group_Header2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Header2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Header2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Head_Group1 = lv_obj_create(ui_Group_Header2);
    lv_obj_set_height(ui_Head_Group1, lv_pct(135));
    lv_obj_set_flex_grow(ui_Head_Group1, 1);
    lv_obj_set_x(ui_Head_Group1, 0);
    lv_obj_set_y(ui_Head_Group1, 6);
    lv_obj_set_align(ui_Head_Group1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Head_Group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Head_Group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Head_Group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Head_Group1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Head_Group1, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Head_Group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Head_Group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Time3 = lv_label_create(ui_Head_Group1);
    lv_obj_set_width(ui_Label_Time3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Time3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Time3, -160);
    lv_obj_set_y(ui_Label_Time3, 0);
    lv_obj_set_align(ui_Label_Time3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Time3, "11:45");
    lv_obj_set_style_text_color(ui_Label_Time3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Time3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Time3, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Temp2 = lv_label_create(ui_Head_Group1);
    lv_obj_set_width(ui_Label_Temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Temp2, -374);
    lv_obj_set_y(ui_Label_Temp2, -1);
    lv_obj_set_align(ui_Label_Temp2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Temp2, "+24.7");
    lv_obj_set_style_text_color(ui_Label_Temp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Temp2, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Celsius2 = lv_label_create(ui_Head_Group1);
    lv_obj_set_width(ui_Label_Celsius2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Celsius2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Celsius2, -352);
    lv_obj_set_y(ui_Label_Celsius2, 0);
    lv_obj_set_align(ui_Label_Celsius2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Celsius2, "°C");
    lv_obj_set_style_text_color(ui_Label_Celsius2, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Celsius2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Celsius2, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Battery_Number1 = lv_label_create(ui_Head_Group1);
    lv_obj_set_width(ui_Label_Battery_Number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Battery_Number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Battery_Number1, 30);
    lv_obj_set_y(ui_Label_Battery_Number1, 0);
    lv_obj_set_align(ui_Label_Battery_Number1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Battery_Number1, "25/57");
    lv_obj_set_style_text_color(ui_Label_Battery_Number1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Battery_Number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Battery_Number1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Battery_Number1, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Battery_Percent1 = lv_label_create(ui_Head_Group1);
    lv_obj_set_width(ui_Label_Battery_Percent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Battery_Percent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Battery_Percent1, 450);
    lv_obj_set_y(ui_Label_Battery_Percent1, 0);
    lv_obj_set_align(ui_Label_Battery_Percent1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Battery_Percent1, "L");
    lv_obj_set_style_text_color(ui_Label_Battery_Percent1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Battery_Percent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Battery_Percent1, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Driving = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Group_Driving, 206);
    lv_obj_set_height(ui_Group_Driving, 52);
    lv_obj_set_x(ui_Group_Driving, -268);
    lv_obj_set_y(ui_Group_Driving, 121);
    lv_obj_set_align(ui_Group_Driving, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_Driving, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Driving, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Driving, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Content = lv_obj_create(ui_Group_Driving);
    lv_obj_set_width(ui_Group_Content, 200);
    lv_obj_set_height(ui_Group_Content, 37);
    lv_obj_set_x(ui_Group_Content, 0);
    lv_obj_set_y(ui_Group_Content, -1);
    lv_obj_set_align(ui_Group_Content, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Group_Content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Content, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeL_ODO1 = lv_label_create(ui_Group_Content);
    lv_obj_set_width(ui_LabeL_ODO1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeL_ODO1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeL_ODO1, 0);
    lv_obj_set_y(ui_LabeL_ODO1, -5);
    lv_obj_set_align(ui_LabeL_ODO1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LabeL_ODO1, "ODO");
    lv_obj_set_style_text_color(ui_LabeL_ODO1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeL_ODO1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeL_ODO1, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_ODO1 = lv_obj_create(ui_Group_Content);
    lv_obj_set_width(ui_Group_ODO1, 94);
    lv_obj_set_height(ui_Group_ODO1, 41);
    lv_obj_set_align(ui_Group_ODO1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Group_ODO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_ODO1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_ODO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_ODO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_ODO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_ODO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_ODO1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_ODO_Number1 = lv_label_create(ui_Group_ODO1);
    lv_obj_set_width(ui_Label_ODO_Number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_ODO_Number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_ODO_Number1, 2);
    lv_obj_set_y(ui_Label_ODO_Number1, -5);
    lv_obj_set_align(ui_Label_ODO_Number1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label_ODO_Number1, "51287.7");
    lv_obj_set_style_text_color(ui_Label_ODO_Number1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_ODO_Number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_ODO_Number1, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km2 = lv_label_create(ui_Group_ODO1);
    lv_obj_set_width(ui_Label_km2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km2, -6);
    lv_obj_set_y(ui_Label_km2, -5);
    lv_obj_set_align(ui_Label_km2, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label_km2, "km");
    lv_obj_set_style_text_color(ui_Label_km2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_km2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_km2, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Map = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Group_Map, 260);
    lv_obj_set_height(ui_Group_Map, 260);
    lv_obj_set_x(ui_Group_Map, 0);
    lv_obj_set_y(ui_Group_Map, 16);
    lv_obj_set_align(ui_Group_Map, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_Map, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Map, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Map, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Map_Bg = lv_img_create(ui_Group_Map);
    lv_img_set_src(ui_Map_Bg, &ui_img_map_demo2_png);
    lv_obj_set_width(ui_Map_Bg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Map_Bg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Map_Bg, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Map_Bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Map_Bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GPS_Knob2 = lv_obj_create(ui_Group_Map);
    lv_obj_set_width(ui_GPS_Knob2, 36);
    lv_obj_set_height(ui_GPS_Knob2, 36);
    lv_obj_set_x(ui_GPS_Knob2, -56);
    lv_obj_set_y(ui_GPS_Knob2, 77);
    lv_obj_set_align(ui_GPS_Knob2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPS_Knob2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GPS_Knob2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GPS_Knob2, lv_color_hex(0xFF7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPS_Knob2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GPS_Knob2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Knob1 = lv_obj_create(ui_Group_Map);
    lv_obj_set_width(ui_GPS_Knob1, 15);
    lv_obj_set_height(ui_GPS_Knob1, 15);
    lv_obj_set_x(ui_GPS_Knob1, -56);
    lv_obj_set_y(ui_GPS_Knob1, 77);
    lv_obj_set_align(ui_GPS_Knob1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPS_Knob1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GPS_Knob1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GPS_Knob1, lv_color_hex(0xC9002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPS_Knob1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Group_Map);
    lv_img_set_src(ui_Image1, &ui_img_gps_bg_png);
    lv_obj_set_width(ui_Image1, 208);
    lv_obj_set_height(ui_Image1, 21);
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 328);

    ui_Label_Trip_Odo = lv_label_create(ui_Group_Map);
    lv_obj_set_width(ui_Label_Trip_Odo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Trip_Odo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Trip_Odo, -30);
    lv_obj_set_y(ui_Label_Trip_Odo, -5);
    lv_obj_set_align(ui_Label_Trip_Odo, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label_Trip_Odo, "28.7");
    lv_obj_set_style_text_color(ui_Label_Trip_Odo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Trip_Odo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Trip_Odo, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Time_Trip = lv_label_create(ui_Group_Map);
    lv_obj_set_width(ui_Label_Time_Trip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Time_Trip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Time_Trip, 90);
    lv_obj_set_y(ui_Label_Time_Trip, -5);
    lv_obj_set_align(ui_Label_Time_Trip, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label_Time_Trip, "00:03");
    lv_obj_set_style_text_color(ui_Label_Time_Trip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Time_Trip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Time_Trip, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km3 = lv_label_create(ui_Group_Map);
    lv_obj_set_width(ui_Label_km3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km3, -6);
    lv_obj_set_y(ui_Label_km3, -5);
    lv_obj_set_align(ui_Label_km3, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label_km3, "km");
    lv_obj_set_style_text_color(ui_Label_km3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_km3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_km3, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 212);
    lv_obj_set_height(ui_Container1, 140);
    lv_obj_set_x(ui_Container1, -130);
    lv_obj_set_y(ui_Container1, -48);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed_Number_2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Speed_Number_2, 180);
    lv_obj_set_height(ui_Speed_Number_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed_Number_2, -15);
    lv_obj_set_y(ui_Speed_Number_2, 0);
    lv_obj_set_align(ui_Speed_Number_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed_Number_2, "132");
    lv_obj_set_style_text_color(ui_Speed_Number_2, lv_color_hex(0xD56920), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed_Number_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Speed_Number_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed_Number_2, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed_Number_1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Speed_Number_1, 180);
    lv_obj_set_height(ui_Speed_Number_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed_Number_1, -23);
    lv_obj_set_y(ui_Speed_Number_1, 0);
    lv_obj_set_align(ui_Speed_Number_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed_Number_1, "132");
    lv_obj_set_style_text_color(ui_Speed_Number_1, lv_color_hex(0xFFE69C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed_Number_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Speed_Number_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed_Number_1, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Speed = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Speed, -60);
    lv_obj_set_y(ui_Label_Speed, -62);
    lv_obj_set_align(ui_Label_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Speed, "Speed");
    lv_obj_set_style_text_color(ui_Label_Speed, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Speed, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_kmh1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label_kmh1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_kmh1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_kmh1, 80);
    lv_obj_set_y(ui_Label_kmh1, 32);
    lv_obj_set_align(ui_Label_kmh1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_kmh1, "km/h");
    lv_obj_set_style_text_color(ui_Label_kmh1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_kmh1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_kmh1, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 188);
    lv_obj_set_height(ui_Container2, 30);
    lv_obj_set_x(ui_Container2, -130);
    lv_obj_set_y(ui_Container2, 34);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgSpeedbg = lv_img_create(ui_Container2);
    lv_img_set_src(ui_ImgSpeedbg, &ui_img_speedbg_small_png);
    lv_obj_set_width(ui_ImgSpeedbg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgSpeedbg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgSpeedbg, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ImgSpeedbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSpeedbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgSpeedfg = lv_img_create(ui_Container2);
    lv_img_set_src(ui_ImgSpeedfg, &ui_img_speed_fg_small_png);
    lv_obj_set_width(ui_ImgSpeedfg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgSpeedfg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgSpeedfg, 40);
    lv_obj_set_y(ui_ImgSpeedfg, 0);
    lv_obj_set_align(ui_ImgSpeedfg, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ImgSpeedfg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSpeedfg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label1, 186);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "0   1    2    3   4    5   6    7   8");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_BG1 = NULL;
    ui_Panel1 = NULL;
    ui_Group_Header2 = NULL;
    ui_Head_Group1 = NULL;
    ui_Label_Time3 = NULL;
    ui_Label_Temp2 = NULL;
    ui_Label_Celsius2 = NULL;
    ui_Label_Battery_Number1 = NULL;
    ui_Label_Battery_Percent1 = NULL;
    ui_Group_Driving = NULL;
    ui_Group_Content = NULL;
    ui_LabeL_ODO1 = NULL;
    ui_Group_ODO1 = NULL;
    ui_Label_ODO_Number1 = NULL;
    ui_Label_km2 = NULL;
    ui_Group_Map = NULL;
    ui_Map_Bg = NULL;
    ui_GPS_Knob2 = NULL;
    ui_GPS_Knob1 = NULL;
    ui_Image1 = NULL;
    ui_Label_Trip_Odo = NULL;
    ui_Label_Time_Trip = NULL;
    ui_Label_km3 = NULL;
    ui_Container1 = NULL;
    ui_Speed_Number_2 = NULL;
    ui_Speed_Number_1 = NULL;
    ui_Label_Speed = NULL;
    ui_Label_kmh1 = NULL;
    ui_Container2 = NULL;
    ui_ImgSpeedbg = NULL;
    ui_ImgSpeedfg = NULL;
    ui_Label1 = NULL;

}
