// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ebike_demo

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_BG1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Group_Header2;
extern lv_obj_t * ui_Head_Group1;
extern lv_obj_t * ui_Label_Time3;
extern lv_obj_t * ui_Label_Temp2;
extern lv_obj_t * ui_Label_Celsius2;
extern lv_obj_t * ui_Label_Battery_Number1;
extern lv_obj_t * ui_Label_Battery_Percent1;
extern lv_obj_t * ui_Group_Driving;
extern lv_obj_t * ui_Group_ODO1;
extern lv_obj_t * ui_Label_km2;
extern lv_obj_t * ui_Label_ODO_Number1;
extern lv_obj_t * ui_LabeL_ODO1;
extern lv_obj_t * ui_Group_Gas;
extern lv_obj_t * ui_Label_L1;
extern lv_obj_t * ui_Label_Gas_Number;
extern lv_obj_t * ui_LabeL_Gas;
extern lv_obj_t * ui_Group_Map;
extern lv_obj_t * ui_Map_Bg;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label_Trip_Odo;
extern lv_obj_t * ui_Label_Time_Trip;
extern lv_obj_t * ui_Label_km3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Speed_Number_2;
extern lv_obj_t * ui_Speed_Number_1;
extern lv_obj_t * ui_Label_Speed;
extern lv_obj_t * ui_Label_kmh1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_ImgSpeedbg;
extern lv_obj_t * ui_ImgSpeedfg;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

